### ISSUE TITLE
Error at running

### ISSUE THREAD

**Issue by brijagstu7** [opersys/binder-explorer-web#4]
I am on an ARM64 phone (OnePlus 7) with Android 11 (PixelExperience), when I tried running I met with these:
```
guacamoleb:/data/local/tmp/dist_arm64 $ ./run
  be Installing /data/local/tmp/dist_arm64/_bin/infolauncher.apk +0ms
  be InfoLauncher started (or already started) +32ms
/data/local/tmp/dist_arm64/ServiceManager.js:209
        let lines = proc.stdout.toString().split(/\n/);
                                ^

TypeError: Cannot read property 'toString' of null
    at VndServiceManager.fetch (/data/local/tmp/dist_arm64/ServiceManager.js:209:33)
    at BinderWatcher.scanBinderServices (/data/local/tmp/dist_arm64/binderWatcher.js:153:51)
    at Timeout._onTimeout (/data/local/tmp/dist_arm64/binderWatcher.js:65:33)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```
So what's going on ?

**Comment by fdgonthier** [comment]
I commend you for trying to run this, at all. Very few have tried and reported to me! Thank you for this.

I think the problem is likely because the "grabservice" binary cannot be run for some reason. I would like to see a whole log for this but I need to first ask on what kind of Android device you've tried to run this? Because of SELinux protections, this program is not going to work on any modern stock Android device. We've tried but Google has long since cut us from the source of information we need to build the Binder Explorer display.

**Comment by brijagstu7** [comment]
@fdgonthier thank you for your concern, I'll post some photos in an app called DevCheck to tell the device I'm using. If you need more feel free to tell me.![Screenshot_20210426-112540.png](https://user-images.githubusercontent.com/56994423/116025069-34feb880-a682-11eb-8668-acf2e1ffddd7.png)![Screenshot_20210426-112453.png](https://user-images.githubusercontent.com/56994423/116025076-38923f80-a682-11eb-9ebb-415ad1b23f99.png)![Screenshot_20210426-112445.png](https://user-images.githubusercontent.com/56994423/116025080-3b8d3000-a682-11eb-8304-c92db2c75d94.png)![Screenshot_20210426-112438.png](https://user-images.githubusercontent.com/56994423/116025082-3d56f380-a682-11eb-8b51-a027694a3262.png)![Screenshot_20210426-112429.png](https://user-images.githubusercontent.com/56994423/116025089-3f20b700-a682-11eb-8eb2-d52ef9a48a01.png)

**Comment by brijagstu7** [comment]
I disabled SELinux (`setenforce 0`) and switched to root and ran again, still failed but the messages differed:
```
guacamoleb:/data/local/tmp/dist_arm64 # ./run
  be Installing /data/local/tmp/dist_arm64/_bin/infolauncher.apk +0ms
  be InfoLauncher started (or already started) +30ms
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/dev/binderfs/binder_logs/state'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:136:12
    at FSReqCallback.oncomplete (fs.js:156:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/dev/binderfs/binder_logs/state'
}
```
I suppose you need `logcat` to see a whole log but that might be way too much from recognizing the true problem.

**Comment by fdgonthier** [comment]
Good job. We're getting somewhere:

`Error: ENOENT: no such file or directory, open '/dev/binderfs/binder_logs/state'`

This means that /dev/binderfs is not mounted or not accessible. You can try this:

```
mkdir /dev/binderfs
mount -t binder binder /dev/binderfs
```

And see if it gets your your `/dev/binderfs`

**Comment by brijagstu7** [comment]
> mount -t binder binder /dev/binderfs

I get `mount: 'binder'->'/dev/binderfs': No such device`

**Comment by brijagstu7** [comment]
Another thing is that `/dev/binderfs` already exists but no content in it

**Comment by mirfatif** [comment]
> > mount -t binder binder /dev/binderfs
> 
> I get `mount: 'binder'->'/dev/binderfs': No such device`

It means that your kernel is not built with [`CONFIG_ANDROID_BINDERFS`](https://github.com/torvalds/linux/blob/v5.17/drivers/android/Kconfig#L23).

I face the same problem when testing with SELinux set `permissive`.

@fdgonthier is `binderfs` a must? If so I'll rebuild my kernel.

Another thing: does `binder-explorer-web` explore only the framework services registered with the system service manager? What about the binder transactions occurring between two apps (e.g. when an app binds to another app's service)? Or what if a process sends a strong Binder reference in an `Intent` to an app, and then both do IPC through that binder? Would such IPC be visible in `binder-explorer-web`?

Thank you.

**Comment by Binozo** [comment]
I am facing the same problem here :/

``````
biscuit_puffin:/data/local/tmp/binder_explorer # ./run
/data/local/tmp/binder_explorer/PackageManager.js:27
lines = proc.stdout.toString().split(/\n/);
^

TypeError: Cannot read property 'toString' of null
at new PackageManager (/data/local/tmp/binder_explorer/PackageManager.js:27:29)
at Object.<anonymous> (/data/local/tmp/binder_explorer/app.js:297:10)
at Module._compile (internal/modules/cjs/loader.js:1137:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
at Module.load (internal/modules/cjs/loader.js:985:32)
at Function.Module._load (internal/modules/cjs/loader.js:878:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
at internal/main/run_main_module.js:17:47
``````

But my target Android is actually a rooted echo dot 2. gen running Android 7.1.2 armv5 if it helps

I got that following error too:
> > mount -t binder binder /dev/binderfs
> 
> I get `mount: 'binder'->'/dev/binderfs': No such device`

**Comment by fdgonthier** [comment]
_binderfs_ is absolutely mandatory for Binder Explorer to work, as it was designed to work to interpret the data available in _binderfs_ to build up its display. If you can't get _binderfs_ to work, you won't get Binder Explorer.

Unfortunately, I no longer work for the company that employed me to work on Binder Explorer. The software is probably accumulating some significant technical debts as Android keeps evolving.

**Comment by Binozo** [comment]
Ok thank you for your quick reply, that Android here I am working here is actually massively stripped down. So I don't think _binderfs_ has any chance to work.

Still an awesome looking project, didn't thought you could run node so easily on that thing😄
